name: Ruff Formatting Check

on:
  push:
    branches:
      - '*' # Runs on all branches for push events
  pull_request:
    branches:
      - '*' # Runs on all branches for PRs

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Ruff
        run: pip install ruff

      - name: Get Changed Python Files
        id: changed_files 
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            const baseRef = process.env.GITHUB_BASE_REF || 'HEAD~1';
            let rawFiles = execSync(`git diff --name-only ${baseRef} HEAD | grep '\\.py$' || true`).toString();
            const files = rawFiles.split('\n').filter(Boolean);

            console.log(`Changed Python files:`, files);
            core.setOutput("changed_files", files.join(' '));

      - name: Debug Changed Files
        run: |
          echo "Changed files output: \"${{ steps.changed_files.outputs.changed_files }}\""
          if [[ -z "${{ steps.changed_files.outputs.changed_files }}" ]]; then echo "No Python files changed."; fi


      - name: Run Ruff Formatting Check on Changed Files
        if: ${{ steps.changed_files.outputs.changed_files != '' }}
        run: |
          echo "Running Ruff on: ${{ steps.changed_files.outputs.changed_files }}"
          echo "${{ steps.changed_files.outputs.changed_files }}" | tr ' ' '\n' | xargs ruff format --check

